# Generated by Django 3.2.7 on 2021-09-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': False, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='medicos',
            options={'managed': False, 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
    ]
